### ISSUE TITLE
fix: investigate juno furnace

### ISSUE THREAD

**Issue by Sen-Com** [White-Whale-Defi-Platform/furnace#97]
> Error: Query failed with (6): rpc error: code = Unknown desc = recovered: account is not a module account
stack:
goroutine 9503847115 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func3({0x23cf280, 0x3670fc0})
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/recovery.go:71 +0x25
github.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func5({0x23cf280?, 0x3670fc0?})
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/recovery.go:39 +0x2d
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x23cf280, 0x3670fc0}, 0xc0d5871dd6?)
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/recovery.go:28 +0x2f
github.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x23cf280, 0x3670fc0}, 0x7fe8a311e678?)
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/recovery.go:33 +0x53
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/baseapp.go:646 +0x138
panic({0x23cf280?, 0x3670fc0?})
	runtime/panic.go:770 +0x132
github.com/cosmos/cosmos-sdk/x/auth/keeper.AccountKeeper.GetModuleAccountAndPermissions({{0x36804e8, 0xc001ce74a0}, {0x36b8610, 0xc001d7eac0}, 0xc001dea4b0, 0x305d010, {0x36825c0, 0xc001ce7700}, {0xc001519230, 0x2b}}, ...)
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/x/auth/keeper/keeper.go:206 +0x499
github.com/cosmos/cosmos-sdk/x/auth/keeper.AccountKeeper.GetModuleAccount(...)
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/x/auth/keeper/keeper.go:222
github.com/CosmosContracts/juno/v22/x/tokenfactory/keeper.Keeper.BlockedAddr({{0x36b8610, 0xc001d7eac0}, {0x36804e8, 0xc001ce7640}, 0xc001deaa20, {0x3685610, 0xc001c54960}, {0x7fe9e876ccb0, 0xc001b482c0}, {0x3676e80, ...}, ...}, ...)
	github.com/CosmosContracts/juno/v22/x/tokenfactory/keeper/bankactions.go:22 +0x236
github.com/CosmosContracts/juno/v22/x/tokenfactory/keeper.Keeper.mintTo({{0x36b8610, 0xc001d7eac0}, {0x36804e8, 0xc001ce7640}, 0xc001deaa20, {0x3685610, 0xc001c54960}, {0x7fe9e876ccb0, 0xc001b482c0}, {0x3676e80, ...}, ...}, ...)
	github.com/CosmosContracts/juno/v22/x/tokenfactory/keeper/bankactions.go:51 +0x1bb
github.com/CosmosContracts/juno/v22/x/tokenfactory/keeper.msgServer.Mint({{{0x36b8610, 0xc001d7eac0}, {0x36804e8, 0xc001ce7640}, 0xc001deaa20, {0x3685610, 0xc001c54960}, {0x7fe9e876ccb0, 0xc001b482c0}, {0x3676e80, ...}, ...}}, ...)
	github.com/CosmosContracts/juno/v22/x/tokenfactory/keeper/msg_server.go:73 +0x25e
github.com/CosmosContracts/juno/v22/x/tokenfactory/types._Msg_Mint_Handler.func1({0x36a15f8?, 0xc02ed9db00?}, {0x27feb40?, 0xc0dd4bc1c0?})
	github.com/CosmosContracts/juno/v22/x/tokenfactory/types/tx.pb.go:986 +0xcb
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x36a14e0, 0xc0dd50e2c8}, {0xc1b4503b28?, 0x412b85?}, 0x2a0?, 0xc11ba84000)
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/msg_service_router.go:118 +0x8a
github.com/CosmosContracts/juno/v22/x/tokenfactory/types._Msg_Mint_Handler({0x2836ba0, 0xc000934a80}, {0x36a14e0, 0xc0dd50e2c8}, 0x305d910, 0xc0dd4d0d00)
	github.com/CosmosContracts/juno/v22/x/tokenfactory/types/tx.pb.go:988 +0x143
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x36a13c8, 0x4e29d20}, {0x36b8d10, 0xc0dd4bc180}, {{0xb, 0x0}, {0xc045b02f52, 0x6}, 0x10869b9, {0x32cd4fb8, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/msg_service_router.go:139 +0x2a7
github.com/CosmWasm/wasmd/x/wasm/keeper.SDKMessageHandler.handleSdkMessage({{_, _}, {_, _}}, {{0x36a13c8, 0x4e29d20}, {0x36b8d10, 0xc0dd4bc180}, {{0xb, 0x0}, ...}, ...}, ...)
	github.com/CosmWasm/wasmd@v0.45.0/x/wasm/keeper/handler_plugin.go:103 +0x208
github.com/CosmWasm/wasmd/x/wasm/keeper.SDKMessageHandler.DispatchMsg({{_, _}, {_, _}}, {{0x36a13c8, 0x4e29d20}, {0x36b8d10, 0xc0dd4bc180}, {{0xb, 0x0}, ...}, ...}, ...)
	github.com/CosmWasm/wasmd@v0.45.0/x/wasm/keeper/handler_plugin.go:73 +0x2ba
github.com/CosmWasm/wasmd/x/wasm/keeper.MessageHandlerChain.DispatchMsg({{_, _, _}}, {{0x36a13c8, 0x4e29d20}, {0x36b8d10, 0xc0dd4bc180}, {{0xb, 0x0}, {0xc045b02f52, ...}, ...}, ...}, ...)
	github.com/CosmWasm/wasmd@v0.45.0/x/wasm/keeper/handler_plugin.go:135 +0x110
github.com/CosmosContracts/juno/v22/x/tokenfactory/bindings.(*CustomMessenger).DispatchMsg(_, {{0x36a13c8, 0x4e29d20}, {0x36b8d10, 0xc0dd4bc180}, {{0xb, 0x0}, {0xc045b02f52, 0x6}, 0x10869b9, ...}, ...}, ...)
	github.com/CosmosContracts/juno/v22/x/tokenfactory/bindings/message_plugin.go:68 +0x1a2
github.com/CosmWasm/wasmd/x/wasm/keeper.MessageHandlerChain.DispatchMsg({{_, _, _}}, {{0x36a13c8, 0x4e29d20}, {0x36b8d10, 0xc0dd4bc180}, {{0xb, 0x0}, {0xc045b02f52, ...}, ...}, ...}, ...)
	github.com/CosmWasm/wasmd@v0.45.0/x/wasm/keeper/handler_plugin.go:135 +0x110
github.com/CosmWasm/wasmd/x/wasm/keeper.MessageDispatcher.DispatchSubmessages({{_, _}, {_, _}}, {{0x36a13c8, 0x4e29d20}, {0x36b8d10, 0xc0dd479e00}, {{0xb, 0x0}, ...}, ...}, ...)
	github.com/CosmWasm/wasmd@v0.45.0/x/wasm/keeper/msg_dispatcher.go:106 +0x489
github.com/CosmWasm/wasmd/x/wasm/keeper.DefaultWasmVMContractResponseHandler.Handle({{_, _}}, {{0x36a13c8, 0x4e29d20}, {0x36b8d10, 0xc0dd479e00}, {{0xb, 0x0}, {0xc045b02f52, 0x6}, ...}, ...}, ...)
	github.com/CosmWasm/wasmd@v0.45.0/x/wasm/keeper/keeper.go:1245 +0xa2
github.com/CosmWasm/wasmd/x/wasm/keeper.(*Keeper).handleContractResponse(_, {{0x36a13c8, 0x4e29d20}, {0x36b8d10, 0xc0dd479e00}, {{0xb, 0x0}, {0xc045b02f52, 0x6}, 0x10869b9, ...}, ...}, ...)
	github.com/CosmWasm/wasmd@v0.45.0/x/wasm/keeper/keeper.go:1034 +0x4a7
github.com/CosmWasm/wasmd/x/wasm/keeper.Keeper.execute({{0x36804e8, 0xc001ce75e0}, {0x36c5460, 0xc001d7eac0}, {0x36854c0, 0xc001c54a00}, {0x3675de0, 0xc001ce7b20}, {0x3675ca0, 0xc000e45480}, ...}, ...)
	github.com/CosmWasm/wasmd@v0.45.0/x/wasm/keeper/keeper.go:403 +0x111e
github.com/CosmWasm/wasmd/x/wasm/keeper.msgServer.ExecuteContract({0xc1b450b0a8?}, {0x36a15f8, 0xc1648cc3f0}, 0xc07ed84d20)
	github.com/CosmWasm/wasmd@v0.45.0/x/wasm/keeper/msg_server.go:128 +0x1eb
github.com/CosmWasm/wasmd/x/wasm/types._Msg_ExecuteContract_Handler.func1({0x36a15f8?, 0xc1648cc3f0?}, {0x27fae00?, 0xc07ed84d20?})
	github.com/CosmWasm/wasmd@v0.45.0/x/wasm/types/tx.pb.go:2263 +0xcb
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x36a14e0, 0xc0dc4e9b88}, {0xc1b450b178?, 0x412b85?}, 0x2a0?, 0xc119ead920)
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/msg_service_router.go:118 +0x8a
github.com/CosmWasm/wasmd/x/wasm/types._Msg_ExecuteContract_Handler({0x27b96e0, 0xc001885b38}, {0x36a14e0, 0xc0dc4e9b88}, 0x305d910, 0xc0dd4154a0)
	github.com/CosmWasm/wasmd@v0.45.0/x/wasm/types/tx.pb.go:2265 +0x143
github.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x36a13c8, 0x4e29d20}, {0x36b8d10, 0xc0dd479e00}, {{0xb, 0x0}, {0xc045b02f52, 0x6}, 0x10869b9, {0x32cd4fb8, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/msg_service_router.go:139 +0x2a7
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x36a13c8, 0x4e29d20}, {0x36b8d10, 0xc0dd479e00}, {{0xb, 0x0}, {0xc045b02f52, 0x6}, 0x10869b9, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/baseapp.go:806 +0x285
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc000e450e0, 0x2, {0xc0dcff6fc0, 0x11a, 0x120})
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/baseapp.go:749 +0xe65
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...)
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/test_helpers.go:25
github.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x36babc0, 0xc002304100}, 0x0, {0xc001020bc0, 0x6}, {0x36c5460, 0xc001037480}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/x/auth/tx/service.go:132 +0x12f
github.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x2759940, 0xc002370000}, {0x36a14e0, 0xc0dc4e9088}, 0xc07ed84be0, 0x0)
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/types/tx/service.pb.go:1416 +0x1a6
github.com/cosmos/cosmos-sdk/baseapp.(*GRPCQueryRouter).RegisterService.func1({{0x36a13c8, 0x4e29d20}, {0x36b8d10, 0xc0dd479cc0}, {{0xb, 0x0}, {0xc045b02f52, 0x6}, 0x10869b9, {0x32cd4fb8, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/grpcrouter.go:82 +0x184
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).handleQueryGRPC(0xc000e450e0, 0xc0021bc3c0, {{0xc06f145200, 0x11d, 0x240}, {0xc06abe1740, 0x23}, 0x10869b9, 0x0})
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/abci.go:698 +0x1a5
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0xc000e450e0, {{0xc06f145200, 0x11d, 0x240}, {0xc06abe1740, 0x23}, 0x10869b9, 0x0})
	github.com/cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/abci.go:545 +0x776
github.com/cometbft/cometbft/abci/client.(*localClient).QuerySync(0xc001dfef00, {{0xc06f145200, 0x11d, 0x240}, {0xc06abe1740, 0x23}, 0x0, 0x0})
	github.com/cometbft/cometbft@v0.37.5/abci/client/local_client.go:259 +0x163
github.com/cometbft/cometbft/proxy.(*appConnQuery).QuerySync(0xc006976e10, {{0xc06f145200, 0x11d, 0x240}, {0xc06abe1740, 0x23}, 0x0, 0x0})
	github.com/cometbft/cometbft@v0.37.5/proxy/app_conn.go:193 +0x1ca
github.com/cometbft/cometbft/rpc/core.ABCIQuery(0xc0059720c0?, {0xc06abe1740?, 0x4?}, {0xc06f145200?, 0x2?, 0x2?}, 0x0?, 0xd3?)
	github.com/cometbft/cometbft@v0.37.5/rpc/core/abci.go:20 +0x9a
reflect.Value.call({0x2525e20?, 0x30612a8?, 0x2873520?}, {0x287e5f1, 0x4}, {0xc0dcdbbd80, 0x5, 0x5?})
	reflect/value.go:596 +0xca6
reflect.Value.Call({0x2525e20?, 0x30612a8?, 0x280?}, {0xc0dcdbbd80?, 0x2873520?, 0x4bd41f?})
	reflect/value.go:380 +0xb9
github.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.makeJSONRPCHandler.func3({0x3699420, 0xc1102a1ed8}, 0xc0dd42c120)
	github.com/cometbft/cometbft@v0.37.5/rpc/jsonrpc/server/http_json_handler.go:108 +0xce6
github.com/cometbft/cometbft/rpc/jsonrpc/server.RegisterRPCFuncs.handleInvalidJSONRPCPaths.func4({0x3699420?, 0xc1102a1ed8?}, 0x40?)
	github.com/cometbft/cometbft@v0.37.5/rpc/jsonrpc/server/http_json_handler.go:140 +0x42
net/http.HandlerFunc.ServeHTTP(0xc000cf6d00?, {0x3699420?, 0xc1102a1ed8?}, 0xc050345990?)
	net/http/server.go:2166 +0x29
net/http.(*ServeMux).ServeHTTP(0x0?, {0x3699420, 0xc1102a1ed8}, 0xc0dd42c120)
	net/http/server.go:2683 +0x1ad
github.com/cometbft/cometbft/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP({{0x3676440?, 0xc000cf6d00?}, 0xd?}, {0x3699420, 0xc1102a1ed8}, 0xc0dd42c120)
	github.com/cometbft/cometbft@v0.37.5/rpc/jsonrpc/server/http_server.go:256 +0xfb
github.com/cometbft/cometbft/rpc/jsonrpc/server.Serve.RecoverAndLogHandler.func1({0x36875f0, 0xc03c120c40}, 0xc0dd42c120)
	github.com/cometbft/cometbft@v0.37.5/rpc/jsonrpc/server/http_server.go:229 +0x26c
net/http.HandlerFunc.ServeHTTP(0x415c25?, {0x36875f0?, 0xc03c120c40?}, 0xc03c120c01?)
	net/http/server.go:2166 +0x29
net/http.serverHandler.ServeHTTP({0x3680ba8?}, {0x36875f0?, 0xc03c120c40?}, 0x6?)
	net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0dc4ee750, {0x36a15f8, 0xc002214b40})
	net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 121
	net/http/server.go:3285 +0x4b4
: panic [cosmos/cosmos-sdk@v0.47.11-0.20240417094812-f556fd956fb1/baseapp/recovery.go:69] With gas wanted: '100000000' and gas used: '199259' : unknown request
    at QueryClient.queryAbci (queryclient.js:118:19)
    at async Object.request (utils.js:31:30)
    at async Object.simulate (queries.js:44:34)
    at async SigningCosmWasmClient.simulate (signingcosmwasmclient.js:94:29)
    at async eval (useSimulateTransaction.ts:10:12)
    at async simulate (useExecuteContract.ts:49:14)

**Comment by Sen-Com** [comment]
The Juno furnce does not work. Sample TX:

https://www.mintscan.io/juno/tx/4505FA93A397F508EA272F27615193D408E00F059AB5F352DA6C189028293E5E
